# CodeRabbit Configuration для Triplex-next Design System
# Дизайн-система SberBusiness на React 18 + TypeScript + Storybook

language: "ru"

early_access: true

# Настройки тона (макс. 250 символов)
tone_instructions: "Будь конструктивным и помогающим. Объясняй причины предложений. Предлагай альтернативы. Фокусируйся на важных проблемах. Отмечай хорошо сделанное."

# База знаний
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - ".github/CODING_GUIDELINES.md"

reviews:
  # Базовые настройки ревью
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  # Автоматическое ревью PR
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - release-0
  
  # Фильтры путей (игнорирование файлов)
  path_filters:
    - "!*.lock"
    - "!*.log"
    - "!node_modules/**"
    - "!dist/**"
    - "!storybook-static/**"
    - "!.loki/**"
    - "!coverage/**"
    - "!public/**"
    - "!.husky/**"
    - "!*.config.js"
    - "!*.config.ts"
    - "!.prettierrc"
    - "!.madgerc"
  
  # Правила для конкретных путей
  path_instructions:
    - path: "src/components/**/*.tsx"
      instructions: |
        - Все props должны иметь TypeScript типы и JSDoc
        - Не должно быть hardcoded цветов (используй токены)
        - Проверь наличие displayName для отладки
        - Compound components должны быть связаны через namespace (Component.Item)
        
    - path: "src/components/**/styles/*.module.less"
      instructions: |
        - Все значения должны использовать CSS переменные или design tokens
        - Не использовать !important без крайней необходимости
        - Классы должны быть в camelCase
        - Поддержка responsive design где уместно
        - Используй CSS переменные для темизации
        
    - path: "**/*.stories.tsx"
      instructions: |
        - Должны быть минимум 2 stories: default, playfround
        - Все props должны быть представлены в Controls (args)
        - Используй Template pattern для переиспользования
        - Добавь MDX документацию для сложных компонентов
        - Stories должны демонстрировать все состояния компонента
        
    - path: "src/components/**/__tests__/*.test.tsx"
      instructions: |
        - Используй describe/it структуру
        - Тестируй все возможные props комбинации
        - Проверяй accessibility (screen reader, keyboard nav)
        - Используй @testing-library/react best practices
        - Покрытие должно быть >80%
        
    - path: "src/components/**/index.ts"
      instructions: |
        - Должен экспортировать только публичное API
        - Экспортируй типы и интерфейсы
        - Не должно быть логики, только exports
        - Named exports предпочтительнее default
        
    - path: "src/index.ts"
      instructions: |
        - Все новые компоненты должны быть экспортированы
        - Группировка exports по категориям (UI, Form, Layout и т.д.)
        - Экспортируй типы вместе с компонентами
        
    - path: "e2e/**/*.spec.ts"
      instructions: |
        - Используй Page Object pattern для переиспользования
        - Тесты должны быть независимыми
        - Ждать элементы через waitFor вместо фиксированных таймаутов
        - Используй test.describe для группировки
        
    - path: "**/*.md"
      instructions: |
        - Документация на русском языке
        - Примеры кода должны быть рабочими
        - Ссылки на Storybook где уместно
        - Четкая структура: Overview, API, Examples, Accessibility

# Автоматические ревьюверы
chat:
  auto_reply: true