# CodeRabbit Configuration для Triplex-next Design System
# Дизайн-система SberBusiness на React 18 + TypeScript + Storybook

language: "ru"

reviews:
  # Базовые настройки ревью
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  # Автоматическое ревью PR
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - release-0

early_access: true

# Глобальные правила для всей дизайн-системы
instructions: |
  ## Общие правила дизайн-системы Triplex
  
  ### Архитектура и структура
  - Каждый компонент должен иметь собственный каталог с файлами: ComponentName.tsx, styles/ComponentName.module.less, index.ts, __tests__/ComponentName.test.tsx
  - Обязательный файл index.ts для каждого компонента для поддержки генерации exports в package.json
  - Все компоненты должны экспортироваться через src/index.ts
  - Используй модульную структуру: один компонент = одна папка со всеми зависимостями
  
  ### TypeScript
  - Все props должны иметь явную типизацию через interface или type
  - Не использовать any, использовать unknown для неопределённых типов
  - Props интерфейсы должны быть экспортированы для переиспользования
  - Используй строгую типизацию: strict mode включен
  - Обязательны JSDoc комментарии для всех публичных props и методов
  
  ### React паттерны
  - Используй функциональные компоненты с hooks
  - Compound components для сложных компонентов (например, Tab.Group, Tab.Item)
  - Forwarded refs для всех UI компонентов через React.forwardRef
  - Мемоизация через React.memo только при необходимости (не по умолчанию)
  
  ### Стилизация
  - Все стили в LESS модулях (*.module.less)
  - Не использовать inline styles или hardcoded значения цветов/размеров
  - Обязательное использование design tokens из системы (токены должны быть в отдельном файле)
  - CSS классы в camelCase
  - Поддержка темизации через CSS переменные
  
  ### Accessibility
  - Все интерактивные элементы должны иметь корректные ARIA атрибуты
  - Поддержка keyboard navigation (Tab, Enter, Escape, стрелки)
  - Семантические HTML теги (button вместо div с onClick)
  - aria-label или aria-labelledby для элементов без видимого текста
  - role атрибуты где необходимо
  
  ### Storybook
  - Каждый компонент должен иметь минимум 2 stories:
    * Default - базовое состояние
    * Playground - все интерактивные варианты
  - Stories должны полностью покрывать все возможные комбинации props
  - Используй Controls (args) для интерактивности
  - Добавляй документацию в stories через JSDoc
  - Stories файлы: ComponentName.stories.tsx
  
  ### Тестирование
  - Unit тесты через Vitest для всей логики
  - React Testing Library для компонентов
  - Минимальное покрытие: 80% (рекомендуется 90%)
  - Тестируй accessibility (toBeAccessible)
  - E2E тесты через Playwright для критичных флоу
  - Visual regression тесты через Chromatic
  
  ### Breaking Changes
  - Breaking changes должны быть явно задокументированы в PR description
  - Следуй семантическому версионированию
  - Deprecated API должны иметь комментарии с альтернативами
  
  ### Naming Conventions
  - Компоненты: PascalCase (Button, DatePicker)
  - Файлы компонентов: PascalCase (Button.tsx)
  - Утилиты и хуки: camelCase (useClickOutside, formatDate)
  - Константы: UPPER_SNAKE_CASE
  - CSS классы: camelCase
  - Types/Interfaces: PascalCase с префиксом по контексту (IButtonProps, TSize)
  
  ### Производительность
  - Избегай ненужных ре-рендеров
  - Code splitting где уместно
  - Оптимизация bundle size (проверяй через npm run build)
  
  ### Документация
  - README для сложных компонентов
  - JSDoc комментарии на русском языке
  - Примеры использования в комментариях

# Правила для конкретных путей
path_instructions:
  - path: "src/components/**/*.tsx"
    instructions: |
      - Все props должны иметь TypeScript типы и JSDoc
      - Не должно быть hardcoded цветов (используй токены)
      - Проверь наличие displayName для отладки
      - Compound components должны быть связаны через namespace (Component.Item)
      
  - path: "src/components/**/styles/*.module.less"
    instructions: |
      - Все значения должны использовать CSS переменные или design tokens
      - Не использовать !important без крайней необходимости
      - Классы должны быть в camelCase
      - Поддержка responsive design где уместно
      - Используй CSS переменные для темизации
      
  - path: "**/*.stories.tsx"
    instructions: |
      - Должны быть минимум 2 stories: default, playfround
      - Все props должны быть представлены в Controls (args)
      - Используй Template pattern для переиспользования
      - Добавь MDX документацию для сложных компонентов
      - Stories должны демонстрировать все состояния компонента
      
  - path: "src/components/**/__tests__/*.test.tsx"
    instructions: |
      - Используй describe/it структуру
      - Тестируй все возможные props комбинации
      - Проверяй accessibility (screen reader, keyboard nav)
      - Используй @testing-library/react best practices
      - Покрытие должно быть >80%
      
  - path: "src/components/**/index.ts"
    instructions: |
      - Должен экспортировать только публичное API
      - Экспортируй типы и интерфейсы
      - Не должно быть логики, только exports
      - Named exports предпочтительнее default
      
  - path: "src/index.ts"
    instructions: |
      - Все новые компоненты должны быть экспортированы
      - Группировка exports по категориям (UI, Form, Layout и т.д.)
      - Экспортируй типы вместе с компонентами
      
  - path: "e2e/**/*.spec.ts"
    instructions: |
      - Используй Page Object pattern для переиспользования
      - Тесты должны быть независимыми
      - Ждать элементы через waitFor вместо фиксированных таймаутов
      - Используй test.describe для группировки
      
  - path: "**/*.md"
    instructions: |
      - Документация на русском языке
      - Примеры кода должны быть рабочими
      - Ссылки на Storybook где уместно
      - Четкая структура: Overview, API, Examples, Accessibility

# Настройки чувствительности
tone_instructions: |
  - Будь конструктивным и помогающим
  - Объясняй причины предложений
  - Предлагай альтернативы, не просто критикуй
  - Фокусируйся на важных проблемах, не придирайся к мелочам
  - Если что-то сделано хорошо - отметь это
  
# Игнорирование файлов
ignore:
  - "*.lock"
  - "*.log"
  - "node_modules/**"
  - "dist/**"
  - "storybook-static/**"
  - ".loki/**"
  - "coverage/**"
  - "public/**"
  - ".husky/**"
  - "*.config.js"
  - "*.config.ts"
  - ".prettierrc"
  - ".madgerc"

# Автоматические ревьюверы
chat:
  auto_reply: true