name: triplex-visual

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.visual
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - npm_cache:/root/.npm
    environment:
      HUSKY: "0"
      CI: "true"
    command: sh -c "npm ci && npm run test-visual:ci"

  update:
    build:
      context: .
      dockerfile: Dockerfile.visual
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - npm_cache:/root/.npm
    environment:
      HUSKY: "0"
      CI: "true"
    command: sh -c "npm ci && npm run test-visual:ci:update"

volumes:
  node_modules:
  npm_cache:
