// Токены компонентов.
import { TDesignTokensComponents } from "./types/DesignTokensTypes";
import { ETriplexNextTheme } from "../ThemeProvider/ETriplexNextTheme";
import { GetTokensValueByTheme } from "./GetTokensValueByTheme";
import {
    AlertContext_Tokens,
    Button_Tokens,
    Checkbox_Tokens,
    FormField_Tokens,
    Radio_Tokens,
    Typography_Tokens,
    Link_Tokens,
    Loader_Tokens,
    Dropdown_Tokens,
    DropdownList_Tokens,
    DropdownMobile_Tokens,
    DropdownMobileList_Tokens,
    Overlay_Tokens,
    TDesignTokensComponentsButtonValue,
    TDesignTokensComponentsCheckboxValue,
    TDesignTokensComponentsFormFieldValue,
    TDesignTokensComponentsRadioValue,
    TDesignTokensComponentsTypographyValue,
    TDesignTokensComponentsLinkValue,
    TDesignTokensComponentsLoaderValue,
    TDesignTokensComponentsAlertContextValue,
    AlertProcess_Tokens,
    TDesignTokensComponentsAlertProcessValue,
    TDesignTokensComponentsDropdownValue,
    TDesignTokensComponentsDropdownListValue,
    TDesignTokensComponentsDropdownMobileValue,
    TDesignTokensComponentsDropdownMobileListValue,
    TDesignTokensComponentsOverlayValue,
    TDesignTokensComponentsListItemValue,
    TDesignTokensComponentsListItemControlsButtonValue,
    TDesignTokensComponentsListMasterValue,
    ListItemControlsButton_Tokens,
    ListMaster_Tokens,
    ListItem_Tokens,
    Body_Tokens,
    TDesignTokensComponentsBodyValue,
    UploadZone_Tokens,
    TDesignTokensComponentsUploadZoneValue,
    TDesignTokensComponentsPaginationValue,
    Pagination_Tokens,
    TDesignTokensComponentsCardValue,
    Card_Tokens,
} from "./components";

export const DesignTokensComponents: TDesignTokensComponents = {
    Button: GetTokensValueByTheme<TDesignTokensComponentsButtonValue>(ETriplexNextTheme.LIGHT, Button_Tokens),
    Checkbox: GetTokensValueByTheme<TDesignTokensComponentsCheckboxValue>(ETriplexNextTheme.LIGHT, Checkbox_Tokens),
    FormField: GetTokensValueByTheme<TDesignTokensComponentsFormFieldValue>(ETriplexNextTheme.LIGHT, FormField_Tokens),
    Link: GetTokensValueByTheme<TDesignTokensComponentsLinkValue>(ETriplexNextTheme.LIGHT, Link_Tokens),
    Loader: GetTokensValueByTheme<TDesignTokensComponentsLoaderValue>(ETriplexNextTheme.LIGHT, Loader_Tokens),
    Dropdown: GetTokensValueByTheme<TDesignTokensComponentsDropdownValue>(ETriplexNextTheme.LIGHT, Dropdown_Tokens),
    DropdownList: GetTokensValueByTheme<TDesignTokensComponentsDropdownListValue>(
        ETriplexNextTheme.LIGHT,
        DropdownList_Tokens,
    ),
    DropdownMobile: GetTokensValueByTheme<TDesignTokensComponentsDropdownMobileValue>(
        ETriplexNextTheme.LIGHT,
        DropdownMobile_Tokens,
    ),
    DropdownMobileList: GetTokensValueByTheme<TDesignTokensComponentsDropdownMobileListValue>(
        ETriplexNextTheme.LIGHT,
        DropdownMobileList_Tokens,
    ),
    Typography: GetTokensValueByTheme<TDesignTokensComponentsTypographyValue>(
        ETriplexNextTheme.LIGHT,
        Typography_Tokens,
    ),
    AlertContext: GetTokensValueByTheme<TDesignTokensComponentsAlertContextValue>(
        ETriplexNextTheme.LIGHT,
        AlertContext_Tokens,
    ),
    AlertProcess: GetTokensValueByTheme<TDesignTokensComponentsAlertProcessValue>(
        ETriplexNextTheme.LIGHT,
        AlertProcess_Tokens,
    ),
    Overlay: GetTokensValueByTheme<TDesignTokensComponentsOverlayValue>(ETriplexNextTheme.LIGHT, Overlay_Tokens),
    ListItem: GetTokensValueByTheme<TDesignTokensComponentsListItemValue>(ETriplexNextTheme.LIGHT, ListItem_Tokens),
    ListItemControlsButton: GetTokensValueByTheme<TDesignTokensComponentsListItemControlsButtonValue>(
        ETriplexNextTheme.LIGHT,
        ListItemControlsButton_Tokens,
    ),
    ListMaster: GetTokensValueByTheme<TDesignTokensComponentsListMasterValue>(
        ETriplexNextTheme.LIGHT,
        ListMaster_Tokens,
    ),
    Body: GetTokensValueByTheme<TDesignTokensComponentsBodyValue>(ETriplexNextTheme.LIGHT, Body_Tokens),
    Radio: GetTokensValueByTheme<TDesignTokensComponentsRadioValue>(ETriplexNextTheme.LIGHT, Radio_Tokens),
    UploadZone: GetTokensValueByTheme<TDesignTokensComponentsUploadZoneValue>(
        ETriplexNextTheme.LIGHT,
        UploadZone_Tokens,
    ),
    Pagination: GetTokensValueByTheme<TDesignTokensComponentsPaginationValue>(
        ETriplexNextTheme.LIGHT,
        Pagination_Tokens,
    ),
    Card: GetTokensValueByTheme<TDesignTokensComponentsCardValue>(ETriplexNextTheme.LIGHT, Card_Tokens),
};
