import { Divider_Tokens } from "./components/Divider";
// Токены локальных компонентов Triplex Next.
import { TDesignTokensComponents } from "./types/DesignTokensTypes";
import { ETriplexNextTheme } from "../ThemeProvider/ETriplexNextTheme";
import { GetTokensValueByTheme } from "./GetTokensValueByTheme";
import {
    AlertContext_Tokens,
    AlertProcess_Tokens,
    Button_Tokens,
    Calendar_Tokens,
    Card_Tokens,
    Checkbox_Tokens,
    Chip_Tokens,
    DropdownList_Tokens,
    DropdownMobileList_Tokens,
    DropdownMobile_Tokens,
    Dropdown_Tokens,
    FooterPage_Tokens,
    FormField_Tokens,
    HeaderPage_Tokens,
    Island_Tokens,
    IslandAccordion_Tokens,
    IslandWidget_Tokens,
    Link_Tokens,
    ListItemControlsButton_Tokens,
    ListItem_Tokens,
    ListMaster_Tokens,
    Loader_Tokens,
    LoaderScreen_Tokens,
    Marker_Tokens,
    MarkerStatus_Tokens,
    MultiselectField_Tokens,
    Overlay_Tokens,
    Pagination_Tokens,
    Radio_Tokens,
    SegmentedControlSegment_Tokens,
    SegmentedControl_Tokens,
    Skeleton_Tokens,
    SMSInput_Tokens,
    Slider_Tokens,
    Step_Tokens,
    Stepper_Tokens,
    TabsLine_Tokens,
    Tabs_Tokens,
    Tag_Tokens,
    TagColor_Tokens,
    Typography_Tokens,
    Tooltip_Tokens,
    UploadZone_Tokens,
    LightBox_Tokens,
    Notification_Tokens,
    StatusTracker_Tokens,
    TDesignTokensComponentsAlertContextValue,
    TDesignTokensComponentsAlertProcessValue,
    TDesignTokensComponentsButtonValue,
    TDesignTokensComponentsCalendarValue,
    TDesignTokensComponentsCardValue,
    TDesignTokensComponentsCheckboxValue,
    TDesignTokensComponentsChipValue,
    TDesignTokensComponentsDividerValue,
    TDesignTokensComponentsDropdownListValue,
    TDesignTokensComponentsDropdownMobileListValue,
    TDesignTokensComponentsDropdownMobileValue,
    TDesignTokensComponentsDropdownValue,
    TDesignTokensComponentsFooterPageValue,
    TDesignTokensComponentsFormFieldValue,
    TDesignTokensComponentsHeaderPageValue,
    TDesignTokensComponentsIslandValue,
    TDesignTokensComponentsIslandAccordionValue,
    TDesignTokensComponentsIslandWidgetValue,
    TDesignTokensComponentsLinkValue,
    TDesignTokensComponentsListItemControlsButtonValue,
    TDesignTokensComponentsListItemValue,
    TDesignTokensComponentsListMasterValue,
    TDesignTokensComponentsLoaderValue,
    TDesignTokensComponentsLoaderScreenValue,
    TDesignTokensComponentsMarkerValue,
    TDesignTokensComponentsMarkerStatusValue,
    TDesignTokensComponentsMultiselectFieldValue,
    TDesignTokensComponentsOverlayValue,
    TDesignTokensComponentsPaginationValue,
    TDesignTokensComponentsRadioValue,
    TDesignTokensComponentsSegmentedControlSegmentValue,
    TDesignTokensComponentsSegmentedControlValue,
    TDesignTokensComponentsSkeletonValue,
    TDesignTokensComponentsSMSInputValue,
    TDesignTokensComponentsSliderValue,
    TDesignTokensComponentsStepValue,
    TDesignTokensComponentsStepperValue,
    TDesignTokensComponentsTabsLineValue,
    TDesignTokensComponentsTabsValue,
    TDesignTokensComponentsTagValue,
    TDesignTokensComponentsTagColorValue,
    TDesignTokensComponentsTooltipValue,
    TDesignTokensComponentsTypographyValue,
    TDesignTokensComponentsUploadZoneValue,
    TDesignTokensComponentsLightBoxValue,
    TDesignTokensComponentsNotificationValue,
    TDesignTokensComponentsTableBasicValue,
    TableBasic_Tokens,
    TDesignTokensComponentsStatusTrackerValue,
    TDesignTokensComponentsModalWindowValue,
    ModalWindow_Tokens,
    TDesignTokensComponentsTopOverlayValue,
    TopOverlay_Tokens,
    SmallInput_Tokens,
    TDesignTokensComponentsSmallInputValue,
} from "./components";

export const DesignTokensComponentsThemeDark: TDesignTokensComponents = {
    AlertContext: GetTokensValueByTheme<TDesignTokensComponentsAlertContextValue>(
        ETriplexNextTheme.DARK,
        AlertContext_Tokens,
    ),
    AlertProcess: GetTokensValueByTheme<TDesignTokensComponentsAlertProcessValue>(
        ETriplexNextTheme.DARK,
        AlertProcess_Tokens,
    ),
    Button: GetTokensValueByTheme<TDesignTokensComponentsButtonValue>(ETriplexNextTheme.DARK, Button_Tokens),
    Calendar: GetTokensValueByTheme<TDesignTokensComponentsCalendarValue>(ETriplexNextTheme.DARK, Calendar_Tokens),
    Card: GetTokensValueByTheme<TDesignTokensComponentsCardValue>(ETriplexNextTheme.DARK, Card_Tokens),
    Checkbox: GetTokensValueByTheme<TDesignTokensComponentsCheckboxValue>(ETriplexNextTheme.DARK, Checkbox_Tokens),
    Chip: GetTokensValueByTheme<TDesignTokensComponentsChipValue>(ETriplexNextTheme.DARK, Chip_Tokens),
    Divider: GetTokensValueByTheme<TDesignTokensComponentsDividerValue>(ETriplexNextTheme.DARK, Divider_Tokens),
    Dropdown: GetTokensValueByTheme<TDesignTokensComponentsDropdownValue>(ETriplexNextTheme.DARK, Dropdown_Tokens),
    DropdownList: GetTokensValueByTheme<TDesignTokensComponentsDropdownListValue>(
        ETriplexNextTheme.DARK,
        DropdownList_Tokens,
    ),
    DropdownMobile: GetTokensValueByTheme<TDesignTokensComponentsDropdownMobileValue>(
        ETriplexNextTheme.DARK,
        DropdownMobile_Tokens,
    ),
    DropdownMobileList: GetTokensValueByTheme<TDesignTokensComponentsDropdownMobileListValue>(
        ETriplexNextTheme.DARK,
        DropdownMobileList_Tokens,
    ),
    FooterPage: GetTokensValueByTheme<TDesignTokensComponentsFooterPageValue>(
        ETriplexNextTheme.DARK,
        FooterPage_Tokens,
    ),
    FormField: GetTokensValueByTheme<TDesignTokensComponentsFormFieldValue>(ETriplexNextTheme.DARK, FormField_Tokens),
    HeaderPage: GetTokensValueByTheme<TDesignTokensComponentsHeaderPageValue>(
        ETriplexNextTheme.DARK,
        HeaderPage_Tokens,
    ),
    Island: GetTokensValueByTheme<TDesignTokensComponentsIslandValue>(ETriplexNextTheme.DARK, Island_Tokens),
    IslandAccordion: GetTokensValueByTheme<TDesignTokensComponentsIslandAccordionValue>(
        ETriplexNextTheme.DARK,
        IslandAccordion_Tokens,
    ),
    IslandWidget: GetTokensValueByTheme<TDesignTokensComponentsIslandWidgetValue>(
        ETriplexNextTheme.DARK,
        IslandWidget_Tokens,
    ),
    Link: GetTokensValueByTheme<TDesignTokensComponentsLinkValue>(ETriplexNextTheme.DARK, Link_Tokens),
    ListItem: GetTokensValueByTheme<TDesignTokensComponentsListItemValue>(ETriplexNextTheme.DARK, ListItem_Tokens),
    ListItemControlsButton: GetTokensValueByTheme<TDesignTokensComponentsListItemControlsButtonValue>(
        ETriplexNextTheme.DARK,
        ListItemControlsButton_Tokens,
    ),
    ListMaster: GetTokensValueByTheme<TDesignTokensComponentsListMasterValue>(
        ETriplexNextTheme.DARK,
        ListMaster_Tokens,
    ),
    Loader: GetTokensValueByTheme<TDesignTokensComponentsLoaderValue>(ETriplexNextTheme.DARK, Loader_Tokens),
    LoaderScreen: GetTokensValueByTheme<TDesignTokensComponentsLoaderScreenValue>(
        ETriplexNextTheme.DARK,
        LoaderScreen_Tokens,
    ),
    Marker: GetTokensValueByTheme<TDesignTokensComponentsMarkerValue>(ETriplexNextTheme.DARK, Marker_Tokens),
    MarkerStatus: GetTokensValueByTheme<TDesignTokensComponentsMarkerStatusValue>(
        ETriplexNextTheme.DARK,
        MarkerStatus_Tokens,
    ),
    MultiselectField: GetTokensValueByTheme<TDesignTokensComponentsMultiselectFieldValue>(
        ETriplexNextTheme.DARK,
        MultiselectField_Tokens,
    ),
    Overlay: GetTokensValueByTheme<TDesignTokensComponentsOverlayValue>(ETriplexNextTheme.DARK, Overlay_Tokens),
    Pagination: GetTokensValueByTheme<TDesignTokensComponentsPaginationValue>(
        ETriplexNextTheme.DARK,
        Pagination_Tokens,
    ),
    Radio: GetTokensValueByTheme<TDesignTokensComponentsRadioValue>(ETriplexNextTheme.DARK, Radio_Tokens),
    SegmentedControl: GetTokensValueByTheme<TDesignTokensComponentsSegmentedControlValue>(
        ETriplexNextTheme.DARK,
        SegmentedControl_Tokens,
    ),
    SegmentedControlSegment: GetTokensValueByTheme<TDesignTokensComponentsSegmentedControlSegmentValue>(
        ETriplexNextTheme.DARK,
        SegmentedControlSegment_Tokens,
    ),
    Skeleton: GetTokensValueByTheme<TDesignTokensComponentsSkeletonValue>(ETriplexNextTheme.DARK, Skeleton_Tokens),
    SMSInput: GetTokensValueByTheme<TDesignTokensComponentsSMSInputValue>(ETriplexNextTheme.DARK, SMSInput_Tokens),
    Slider: GetTokensValueByTheme<TDesignTokensComponentsSliderValue>(ETriplexNextTheme.DARK, Slider_Tokens),
    Step: GetTokensValueByTheme<TDesignTokensComponentsStepValue>(ETriplexNextTheme.DARK, Step_Tokens),
    Stepper: GetTokensValueByTheme<TDesignTokensComponentsStepperValue>(ETriplexNextTheme.DARK, Stepper_Tokens),
    TableBasic: GetTokensValueByTheme<TDesignTokensComponentsTableBasicValue>(
        ETriplexNextTheme.DARK,
        TableBasic_Tokens,
    ),
    Tabs: GetTokensValueByTheme<TDesignTokensComponentsTabsValue>(ETriplexNextTheme.DARK, Tabs_Tokens),
    Tag: GetTokensValueByTheme<TDesignTokensComponentsTagValue>(ETriplexNextTheme.DARK, Tag_Tokens),
    TagColor: GetTokensValueByTheme<TDesignTokensComponentsTagColorValue>(ETriplexNextTheme.DARK, TagColor_Tokens),
    TabsLine: GetTokensValueByTheme<TDesignTokensComponentsTabsLineValue>(ETriplexNextTheme.DARK, TabsLine_Tokens),
    Tooltip: GetTokensValueByTheme<TDesignTokensComponentsTooltipValue>(ETriplexNextTheme.DARK, Tooltip_Tokens),
    Typography: GetTokensValueByTheme<TDesignTokensComponentsTypographyValue>(
        ETriplexNextTheme.DARK,
        Typography_Tokens,
    ),
    UploadZone: GetTokensValueByTheme<TDesignTokensComponentsUploadZoneValue>(
        ETriplexNextTheme.DARK,
        UploadZone_Tokens,
    ),
    LightBox: GetTokensValueByTheme<TDesignTokensComponentsLightBoxValue>(ETriplexNextTheme.DARK, LightBox_Tokens),
    Notification: GetTokensValueByTheme<TDesignTokensComponentsNotificationValue>(
        ETriplexNextTheme.DARK,
        Notification_Tokens,
    ),
    StatusTracker: GetTokensValueByTheme<TDesignTokensComponentsStatusTrackerValue>(
        ETriplexNextTheme.DARK,
        StatusTracker_Tokens,
    ),
    ModalWindow: GetTokensValueByTheme<TDesignTokensComponentsModalWindowValue>(
        ETriplexNextTheme.DARK,
        ModalWindow_Tokens,
    ),
    TopOverlay: GetTokensValueByTheme<TDesignTokensComponentsTopOverlayValue>(
        ETriplexNextTheme.DARK,
        TopOverlay_Tokens,
    ),
    SmallInput: GetTokensValueByTheme<TDesignTokensComponentsSmallInputValue>(
        ETriplexNextTheme.DARK,
        SmallInput_Tokens,
    ),
};
